import Link from "next/link";
import { notFound } from "next/navigation";
import { recalculateProductAction, saveProductCostsAction, saveProductShippingAction } from "../../profitability-actions";
import { requireWorkspaceContext } from "@/lib/server/auth/workspace-context";
import { loadProductProfitability } from "@/lib/server/services/profitability-service";

export default async function ProductProfitPage({ params, searchParams }: { params: Promise<{id:string}>; searchParams: Promise<{destination?:string}> }) {
  const {id}=await params; const {destination}=await searchParams;
  const view=await loadProductProfitability(await requireWorkspaceContext(),id,destination); if(!view) notFound();
  const {product,inputs,calculation}=view.selected; const result=calculation.result; const cost=product.costVersions[0]; const shipping=product.shippingOverrides.find((row)=>row.destinationCountry===view.destination); const listing=product.etsyListingLinks[0]?.listing;
  return <div className="mx-auto max-w-5xl space-y-6"><header><Link className="text-sm underline" href="/app/products">← Ürünler</Link><p className="eyebrow mt-4">Product profitability</p><h1 className="mt-2 text-3xl font-semibold">{product.title}</h1><p className="mt-2 text-sm text-stone-600">{listing?`${listing.priceAmount.toString()} ${listing.priceCurrency} · ${view.destination}`:"Etsy ilanı bağlı değil"}</p></header>
    <div className="grid gap-3 sm:grid-cols-3"><Metric label="Nakit kâr" value={result?`${result.finalCashProfit.toDecimalPlaces(2)} ${result.reportingCurrency}`:"—"}/><Metric label="Ekonomik kâr" value={result?.economicProfit?`${result.economicProfit.toDecimalPlaces(2)} ${result.reportingCurrency}`:"—"}/><Metric label="Nakit marj" value={result?.cashMarginPercent?`%${result.cashMarginPercent.toDecimalPlaces(1)}`:"—"}/></div>
    <section className="card p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">Hesaplama durumu · {calculation.status}</h2><p className="mt-1 text-sm text-stone-600">Tamlık {calculation.completenessScore}/100</p></div><form action={recalculateProductAction}><input type="hidden" name="productId" value={id}/><input type="hidden" name="destinationCountry" value={view.destination}/><button className="rounded-xl bg-jade px-4 py-2.5 text-sm font-medium text-white">Yeni değişmez snapshot oluştur</button></form></div>{calculation.warnings.length?<ul className="mt-4 space-y-1 text-sm text-amber-800">{calculation.warnings.map((warning)=><li key={warning}>• {warning}</li>)}</ul>:null}</section>
    {result?<div className="grid gap-4 lg:grid-cols-2"><Breakdown title="Gelir ve ücretler" rows={[["Gelir",result.grossRevenue],["Etsy ücretleri",result.etsyFees],["Vergi öncesi nakit kâr",result.preTaxCashProfit],["Planlama rezervi",result.taxReserve]]} currency={result.reportingCurrency}/><Breakdown title="Ürün ve lojistik" rows={[["Ürün nakit maliyeti",result.productCashCost],["Ekonomik emek",result.economicLabourCost],["Paketleme",result.packagingCost],["Kargo",result.shippingCost],["Gümrük riski",result.customsExposure]]} currency={result.reportingCurrency}/><section className="card p-5 lg:col-span-2"><h2 className="font-semibold">Fiyat önerisi</h2><div className="mt-4 grid gap-3 sm:grid-cols-5">{Object.entries(calculation.recommendations!).filter(([key])=>key!=="marketplaceCurrency").map(([key,value])=><Metric key={key} label={key} value={value?`${value.toString()} ${inputs.marketplaceCurrency}`:"—"}/>)}</div><p className="mt-3 text-xs text-stone-500">Her aday fiyatta yüzde ve sabit Etsy ücretleri yeniden hesaplanır. Etsy fiyatı değiştirilmez.</p></section></div>:null}
    <div className="grid gap-4 lg:grid-cols-2"><section className="card p-5"><h2 className="font-semibold">Ürün maliyetlerini güncelle</h2><form action={saveProductCostsAction} className="mt-4 grid gap-3 sm:grid-cols-2"><input type="hidden" name="productId" value={id}/><Field name="materialCost" label="Malzeme" value={cost?.materialCostTry.toString()}/><Field name="labourHours" label="Emek saati" value={cost?.laborHours.toString()}/><Field name="cashLabourRate" label="Saatlik nakit emek" value={cost?.laborHourlyRateTry.toString()}/><Field name="economicLabourRate" label="Ekonomik saat değeri (opsiyonel)" value={cost?.economicHourlyRateTry?.toString()} required={false}/><Field name="packagingCost" label="Paketleme" value={cost?.packagingCostTry.toString()}/><Field name="otherDirectCost" label="Diğer doğrudan maliyet" value={cost?.additionalDirectCostTry.toString()}/><Field name="wastageRate" label="Fire yüzdesi" value={cost?.wastageRate.toString()}/><button className="rounded-xl border bg-white px-4 py-2.5 text-sm font-medium sm:col-span-2">Yeni maliyet sürümü oluştur</button></form></section>
    <section className="card p-5"><h2 className="font-semibold">Ürüne özel kargo · {view.destination}</h2><form action={saveProductShippingAction} className="mt-4 grid gap-3 sm:grid-cols-2"><input type="hidden" name="productId" value={id}/><input type="hidden" name="destinationCountry" value={view.destination}/><Field name="shippingCost" label="Kargo (bilinmiyorsa boş)" value={shipping?.shippingCost?.toString()} required={false}/><Field name="shippingCurrency" label="Kargo para birimi" value={shipping?.shippingCurrency??inputs.costCurrency}/><label className="text-sm">Gümrük sorumluluğu<select name="customsResponsibility" defaultValue={shipping?.customsResponsibility??inputs.customsResponsibility} className="mt-1 w-full rounded-lg border px-3 py-2"><option>UNKNOWN</option><option>SELLER</option><option>BUYER</option></select></label><Field name="sellerPaidCustomsCost" label="Satıcı gümrük maliyeti" value={shipping?.sellerPaidCustomsCost?.toString()} required={false}/><Field name="customsCurrency" label="Gümrük para birimi" value={shipping?.customsCurrency??inputs.marketplaceCurrency} required={false}/><button className="rounded-xl border bg-white px-4 py-2.5 text-sm font-medium sm:col-span-2">Yeni lojistik sürümü oluştur</button></form></section></div>
    <section className="card p-5"><h2 className="font-semibold">Snapshot geçmişi</h2>{product.profitSnapshots.length?<div className="mt-3 divide-y">{product.profitSnapshots.map((snapshot)=><div className="grid gap-1 py-3 text-sm sm:grid-cols-4" key={snapshot.id}><span>{snapshot.calculatedAt.toLocaleString("tr-TR")}</span><span>{snapshot.status}</span><span>{snapshot.finalCashProfit?.toString()??"—"} {snapshot.reportingCurrency}</span><span>engine {snapshot.engineVersion}</span></div>)}</div>:<p className="mt-3 text-sm text-stone-600">Henüz kaydedilmiş hesaplama snapshot’ı yok.</p>}</section>
  </div>;
}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-xl border bg-white p-4"><p className="text-xs text-stone-500">{label}</p><p className="mt-2 break-words font-semibold">{value}</p></div>}
function Field({name,label,value,required=true}:{name:string;label:string;value?:string;required?:boolean}){return <label className="text-sm">{label}<input name={name} inputMode="decimal" required={required} defaultValue={value??""} className="mt-1 w-full rounded-lg border px-3 py-2"/></label>}
function Breakdown({title,rows,currency}:{title:string;rows:[string,import("decimal.js").default|null][];currency:string}){return <section className="card p-5"><h2 className="font-semibold">{title}</h2><dl className="mt-3 space-y-2">{rows.map(([label,value])=><div className="flex justify-between gap-4 text-sm" key={label}><dt className="text-stone-600">{label}</dt><dd>{value===null?"—":`${value.toDecimalPlaces(2)} ${currency}`}</dd></div>)}</dl></section>}
