"use server";
import { z } from "zod";
import { requireAdmin } from "@/lib/auth/require-admin";
import { prisma } from "@/lib/prisma";
import { calculate } from "@/lib/domain/calculator";
import { defaultCalculatorInput } from "@/lib/domain/defaults";
import { redirect } from "next/navigation";

const schema = z.object({ receiptId: z.string().min(1), businessProfileVersionId: z.string().min(1), feeProfileId: z.string().min(1), exchangeRateSnapshotId: z.string().min(1), shippingQuoteId: z.string().min(1), customsQuoteId: z.string().min(1), productCostVersionIds: z.record(z.string(), z.string().min(1)) });
export async function confirmEtsyReceiptImport(input: unknown) {
  await requireAdmin({ redirectTo: "/etsy-import" }); const value = schema.parse(input);
  return prisma.$transaction(async (tx) => {
    const receipt = await tx.etsyReceipt.findUniqueOrThrow({ where: { id: value.receiptId }, include: { items: { include: { listing: { include: { productLink: true } } } } } });
    if (receipt.localOrderId) throw new Error("This Etsy receipt is already linked to a local order.");
    const productIds = receipt.items.map((item) => item.listing?.productLink?.productId); if (productIds.some((id) => !id)) throw new Error("Every receipt item must be linked to a local product.");
    const [business, fee, exchange, shipping, customs, costs] = await Promise.all([tx.businessProfileVersion.findUniqueOrThrow({ where: { id: value.businessProfileVersionId } }), tx.feeProfile.findUniqueOrThrow({ where: { id: value.feeProfileId } }), tx.exchangeRateSnapshot.findUniqueOrThrow({ where: { id: value.exchangeRateSnapshotId } }), tx.shippingQuote.findUniqueOrThrow({ where: { id: value.shippingQuoteId } }), tx.customsQuote.findUniqueOrThrow({ where: { id: value.customsQuoteId } }), tx.productCostVersion.findMany({ where: { id: { in: Object.values(value.productCostVersionIds) } } })]);
    const totals = costs.reduce((all, cost) => ({ material: all.material.plus(cost.materialCostTry), laborCost: all.laborCost.plus(cost.laborHours.mul(cost.laborHourlyRateTry)), packaging: all.packaging.plus(cost.packagingCostTry), other: all.other.plus(cost.additionalDirectCostTry) }), { material: receipt.totalAmount.mul(0), laborCost: receipt.totalAmount.mul(0), packaging: receipt.totalAmount.mul(0), other: receipt.totalAmount.mul(0) });
    const customDuty = customs.customsDutyAmount ?? customs.declaredValue.mul(customs.customsDutyRate).div(100); const tariff = customs.additionalTariffAmount ?? customs.declaredValue.mul(customs.additionalTariffRate).div(100);
    const result = calculate({ ...defaultCalculatorInput, itemSubtotalUsd: receipt.subtotalAmount, shippingChargedToBuyerUsd: receipt.shippingAmount, sellerFundedDiscountUsd: receipt.discountAmount, taxCollectedFromBuyerUsd: receipt.taxAmount, materialCostTry: totals.material, laborHours: 1, laborHourlyRateTry: totals.laborCost, packagingCostTry: totals.packaging, additionalDirectCostTry: totals.other, internationalShippingUsd: shipping.shippingCost, shippingInsuranceUsd: shipping.insuranceCost, customsDutyUsd: customDuty, additionalTariffUsd: tariff, carrierProcessingFeeUsd: customs.carrierProcessingFee, brokerageFeeUsd: customs.brokerageFee, customsClearanceFeeUsd: customs.customsClearanceFee, destinationFeesUsd: customs.otherDestinationFee, usdTryRate: exchange.rate, businessStatus: business.businessStatus as typeof defaultCalculatorInput.businessStatus, vatTreatment: business.etsyVatTreatment === "ETSY_CHARGES_SELLER_FEE_VAT" ? "CHARGED_BY_ETSY" : "NOT_CHARGED_BY_ETSY" });
    const order = await tx.order.create({ data: { orderNumber: `ETSY-${receipt.etsyReceiptId}`, orderDate: receipt.sourceCreatedAt, marketplace: "Etsy", destinationCountry: receipt.destinationCountry || "UNKNOWN", destinationRegion: receipt.destinationRegion, currency: receipt.currency, orderStatus: "IMPORTED_CONFIRMED", businessProfileVersionId: business.id, feeProfileId: fee.id, exchangeRateSnapshotId: exchange.id, shippingQuoteId: shipping.id, customsQuoteId: customs.id } });
    for (const item of receipt.items) { const productId = item.listing!.productLink!.productId; const costVersionId = value.productCostVersionIds[item.etsyTransactionId]; if (!costVersionId) throw new Error("Missing product cost version."); await tx.orderItem.create({ data: { orderId: order.id, productId, quantity: item.quantity, unitPrice: item.priceAmount, unitCurrency: item.currency, sellerFundedDiscount: 0, etsyFundedDiscount: 0, shippingAllocated: 0, giftWrapAllocated: 0, taxCollectedByMarketplace: 0, productCostVersionId: costVersionId } }); }
    const snapshot = await tx.orderCostSnapshot.create({ data: { orderId: order.id, businessProfileVersionId: business.id, feeProfileId: fee.id, exchangeRateSnapshotId: exchange.id, grossRevenueUsd: result.totals.grossRevenue, totalCostUsd: result.totals.totalCostUsd, totalCostTry: result.totals.totalCostTry, estimatedProfitUsd: result.totals.estimatedAfterReserveProfit, estimatedProfitTry: result.totals.estimatedAfterReserveProfitTry, assumptionsJson: JSON.stringify(result.assumptions), lines: { create: result.lines.map((line) => ({ formulaName: line.name, category: line.category, calculationBase: line.base, rate: line.rate, sourceAmount: line.nativeAmount, sourceCurrency: line.nativeCurrency, convertedAmountUsd: line.usd, convertedAmountTry: line.try, exchangeRateUsed: exchange.rate, applicableProfileName: business.name, applicableFeeVersion: fee.name, metadataJson: JSON.stringify({ formula: line.formula }) })) } } });
    await tx.etsyReceipt.update({ where: { id: receipt.id }, data: { localOrderId: order.id, needsReconciliation: false } }); await tx.auditLog.create({ data: { entityType: "OrderCostSnapshot", entityId: snapshot.id, action: "CREATED_FROM_ETSY_RECEIPT", actor: "ADMIN", afterJson: JSON.stringify({ receiptId: receipt.etsyReceiptId, orderId: order.id }) } }); return snapshot;
  });
}

export async function confirmEtsyReceiptFormAction(formData: FormData) {
  await requireAdmin({ redirectTo: "/etsy-import" });
  const productCostVersionIds = Object.fromEntries(Array.from(formData.entries()).filter(([key]) => key.startsWith("cost:")).map(([key, value]) => [key.slice(5), String(value)]));
  await confirmEtsyReceiptImport({ receiptId: formData.get("receiptId"), businessProfileVersionId: formData.get("businessProfileVersionId"), feeProfileId: formData.get("feeProfileId"), exchangeRateSnapshotId: formData.get("exchangeRateSnapshotId"), shippingQuoteId: formData.get("shippingQuoteId"), customsQuoteId: formData.get("customsQuoteId"), productCostVersionIds });
  redirect("/orders");
}
