import { ShieldCheck } from "lucide-react";
import { requireAdmin } from "@/lib/auth/require-admin";
import { prisma } from "@/lib/prisma";
import { LogoutButton } from "@/components/logout-button";

export default async function SecurityPage() {
  const session = await requireAdmin({ redirectTo: "/settings/security" });
  const [attempts, events] = await Promise.all([prisma.loginAttempt.findMany({ orderBy: { createdAt: "desc" }, take: 10 }), prisma.adminSecurityEvent.findMany({ orderBy: { createdAt: "desc" }, take: 10 })]);
  return <div className="mx-auto max-w-5xl space-y-6"><header className="flex items-end justify-between gap-4"><div><p className="eyebrow">Settings · Security</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Admin security</h1><p className="mt-2 text-sm text-stone-500">Persistent lockout records, session controls, and privacy-safe event history.</p></div><LogoutButton/></header><section className="grid gap-4 sm:grid-cols-3"><Card label="Authenticated admin" value={session.user.email || "Configured admin"}/><Card label="Role" value="ADMIN"/><Card label="Session maximum" value={`${process.env.AUTH_SESSION_MAX_AGE_HOURS || "8"} hours`}/></section><section className="card p-5"><div className="flex gap-3"><ShieldCheck className="text-jade"/><div><h2 className="font-semibold">Password hash setup</h2><p className="mt-1 text-sm leading-6 text-stone-500">Run <code className="rounded bg-stone-100 px-1.5 py-1">npm run auth:hash-password</code>, then store only the printed bcrypt hash in <code>ADMIN_PASSWORD_HASH</code>. Rotate <code>AUTH_SECRET</code> to invalidate all sessions.</p></div></div></section><div className="grid gap-5 lg:grid-cols-2"><EventTable title="Recent login attempts" rows={attempts.map((item) => ({ at: item.createdAt, status: item.successful ? "Success" : "Rejected", reason: item.reasonCode }))}/><EventTable title="Recent security events" rows={events.map((item) => ({ at: item.createdAt, status: item.successful ? "Success" : "Rejected", reason: item.reasonCode }))}/></div></div>;
}
function Card({ label, value }: { label: string; value: string }) { return <div className="card p-5"><p className="text-xs text-stone-500">{label}</p><p className="mt-2 break-all font-semibold">{value}</p></div>; }
function EventTable({ title, rows }: { title: string; rows: { at: Date; status: string; reason: string }[] }) { return <section className="card overflow-hidden"><h2 className="border-b p-5 font-semibold">{title}</h2><div>{rows.length ? rows.map((row, index) => <div key={`${row.at.toISOString()}-${index}`} className="flex items-center justify-between border-b px-5 py-3 text-sm last:border-0"><div><p>{row.status}</p><p className="mt-1 text-xs text-stone-400">{row.at.toLocaleString("en-GB")}</p></div><span className="pill border-stone-200 bg-stone-50">{row.reason}</span></div>) : <p className="p-5 text-sm text-stone-400">No security events yet.</p>}</div></section>; }
