"use client";

import { useMemo, useState } from "react";
import Decimal from "decimal.js";
import { AlertTriangle, ChevronDown, Info, RotateCcw } from "lucide-react";
import { calculate, solvePrice } from "@/lib/domain/calculator";
import { defaultCalculatorInput } from "@/lib/domain/defaults";
import { formatMoney } from "@/lib/domain/money";
import type { CalculatorInput } from "@/lib/domain/types";

type Tab = "quick" | "reverse" | "company";
const costKeys = ["materialCostTry", "laborHours", "laborHourlyRateTry", "packagingCostTry"] as const;

export function CalculatorWorkspace() {
  const [input, setInput] = useState<CalculatorInput>({ ...defaultCalculatorInput });
  const [tab, setTab] = useState<Tab>("quick");
  const [targetProfit, setTargetProfit] = useState("50");
  const [targetMargin, setTargetMargin] = useState("30");
  const result = useMemo(() => calculate(input), [input]);
  const set = (key: keyof CalculatorInput, value: string | boolean) => setInput((current) => ({ ...current, [key]: value }));
  const reverseProfit = useMemo(() => solvePrice(input, { kind: "profitUsd", value: targetProfit || 0 }), [input, targetProfit]);
  const reverseMargin = useMemo(() => solvePrice(input, { kind: "margin", value: targetMargin || 0 }), [input, targetMargin]);

  return <div className="mx-auto max-w-[1500px] space-y-6">
    <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Calculation workspace</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.035em]">Price with every assumption visible.</h1><p className="mt-2 max-w-2xl text-sm text-stone-500">Native TRY costs stay in TRY. Every converted result uses the displayed USD/TRY snapshot.</p></div><button onClick={() => setInput({ ...defaultCalculatorInput })} className="inline-flex items-center justify-center gap-2 rounded-xl border bg-white px-4 py-2.5 text-sm"><RotateCcw size={15}/> Reset example</button></header>
    <div className="flex w-fit max-w-full gap-1 overflow-x-auto rounded-xl border bg-white p-1">{(["quick", "reverse", "company"] as Tab[]).map((item) => <button key={item} onClick={() => setTab(item)} className={`whitespace-nowrap rounded-lg px-4 py-2 text-sm font-medium ${tab === item ? "bg-[#18342e] text-white" : "text-stone-500 hover:bg-stone-50"}`}>{item === "quick" ? "Quick calculator" : item === "reverse" ? "Reverse pricing" : "Company comparison"}</button>)}</div>
    {tab === "quick" && <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_440px]">
      <div className="space-y-5">
        <InputSection title="Sale & marketplace" hint="USD revenue and Etsy triggers"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><NumberField label="Sale price" value={input.itemSubtotalUsd} suffix="USD" onChange={(v) => set("itemSubtotalUsd", v)}/><NumberField label="Shipping charged" value={input.shippingChargedToBuyerUsd} suffix="USD" onChange={(v) => set("shippingChargedToBuyerUsd", v)}/><NumberField label="Seller discount" value={input.sellerFundedDiscountUsd} suffix="USD" onChange={(v) => set("sellerFundedDiscountUsd", v)}/><NumberField label="USD / TRY snapshot" value={input.usdTryRate} suffix="TRY" onChange={(v) => set("usdTryRate", v)}/><Toggle label="Currency conversion" checked={input.currencyConversionRequired} onChange={(v) => set("currencyConversionRequired", v)}/><Toggle label="Offsite Ads (15%)" checked={input.offsiteAdAttributed} onChange={(v) => set("offsiteAdAttributed", v)}/></div></InputSection>
        <InputSection title="Product cost" hint="Stored in native TRY"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{costKeys.map((key) => <NumberField key={key} label={({materialCostTry:"Material", laborHours:"Labor hours", laborHourlyRateTry:"Hourly rate", packagingCostTry:"Packaging"} as const)[key]} value={input[key]} suffix={key === "laborHours" ? "hours" : "TRY"} onChange={(v) => set(key, v)}/>)}</div><p className="mt-4 rounded-lg bg-amber-50 px-3 py-2 text-xs text-amber-800">Product costs are intentionally not prefilled. Enter MarmaraMade&apos;s actual TRY costs.</p></InputSection>
        <InputSection title="Shipping & DDP customs" hint="Manual dated quotes"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><NumberField label="International shipping" value={input.internationalShippingUsd} suffix="USD" onChange={(v) => set("internationalShippingUsd", v)}/><NumberField label="Customs duty" value={input.customsDutyUsd} suffix="USD" onChange={(v) => set("customsDutyUsd", v)}/><NumberField label="Additional tariff" value={input.additionalTariffUsd} suffix="USD" onChange={(v) => set("additionalTariffUsd", v)}/><NumberField label="Carrier processing" value={input.carrierProcessingFeeUsd} suffix="USD" onChange={(v) => set("carrierProcessingFeeUsd", v)}/><NumberField label="Domestic transfer" value={input.domesticTransferCostTry} suffix="TRY" onChange={(v) => set("domesticTransferCostTry", v)}/><div className="rounded-xl border border-emerald-200 bg-emerald-50 p-3"><span className="pill border-emerald-200 bg-white text-emerald-700">DDP · US</span><p className="mt-2 text-xs leading-4 text-emerald-800">40 × 30 × 7 cm · 1.68 kg billable</p></div></div><p className="mt-3 flex gap-2 text-xs text-stone-500"><Info size={14} className="shrink-0"/> The $4.50 line is a destination carrier customs-processing charge, not a ShipEntegra service.</p></InputSection>
        <InputSection title="Reserves & overhead" hint="Planning entries, not official tax"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><NumberField label="Monthly overhead" value={input.monthlyOverheadTry} suffix="TRY" onChange={(v) => set("monthlyOverheadTry", v)}/><NumberField label="Expected orders" value={input.expectedMonthlyOrders} suffix="orders" onChange={(v) => set("expectedMonthlyOrders", v)}/><NumberField label="Return reserve" value={input.returnReserveRate} suffix="%" onChange={(v) => set("returnReserveRate", v)}/><NumberField label="Tax reserve" value={input.taxReserveRate} suffix="%" onChange={(v) => set("taxReserveRate", v)}/></div></InputSection>
      </div>
      <ResultPanel result={result}/>
    </div>}
    {tab === "reverse" && <ReverseView input={input} targetProfit={targetProfit} targetMargin={targetMargin} setTargetProfit={setTargetProfit} setTargetMargin={setTargetMargin} reverseProfit={reverseProfit} reverseMargin={reverseMargin}/>} 
    {tab === "company" && <CompanyView input={input}/>} 
  </div>;
}

function InputSection({ title, hint, children }: { title: string; hint: string; children: React.ReactNode }) { return <section className="card p-5 sm:p-6"><div className="mb-5 flex items-baseline justify-between gap-3"><h2 className="font-semibold">{title}</h2><span className="text-xs text-stone-400">{hint}</span></div>{children}</section>; }
function NumberField({ label, value, suffix, onChange }: { label: string; value: Decimal.Value; suffix: string; onChange: (value: string) => void }) { return <label className="block"><span className="mb-1.5 block text-xs font-medium text-stone-600">{label}</span><div className="relative"><input className="field pr-14" type="number" min="0" step="0.01" value={String(value)} onChange={(e) => onChange(e.target.value || "0")}/><span className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-[10px] font-semibold text-stone-400">{suffix}</span></div></label>; }
function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) { return <label className="flex cursor-pointer items-center justify-between rounded-xl border bg-stone-50/50 px-3 py-2.5 text-sm"><span>{label}</span><input type="checkbox" className="h-4 w-4 accent-jade" checked={checked} onChange={(e) => onChange(e.target.checked)}/></label>; }

function ResultPanel({ result }: { result: ReturnType<typeof calculate> }) {
  const t = result.totals;
  return <aside className="space-y-5 xl:sticky xl:top-8 xl:self-start"><div className="overflow-hidden rounded-2xl bg-[#18342e] text-white shadow-soft"><div className="border-b border-white/10 p-6"><p className="text-xs font-medium text-white/50">Estimated profit after reserves</p><p className="mt-2 text-4xl font-semibold tracking-tight">{formatMoney(t.estimatedAfterReserveProfit, "USD")}</p><p className="mt-2 text-sm text-[#dbe8b6]">{formatMoney(t.estimatedAfterReserveProfitTry, "TRY")} · {t.afterReserveMargin.toFixed(1)}% margin</p></div><div className="grid grid-cols-2 gap-px bg-white/10"><ResultStat label="Contribution" value={formatMoney(t.contributionProfit, "USD")}/><ResultStat label="Operating" value={formatMoney(t.operatingProfit, "USD")}/><ResultStat label="Total cost · USD" value={formatMoney(t.totalCostUsd, "USD")}/><ResultStat label="Total cost · TRY" value={formatMoney(t.totalCostTry, "TRY")}/></div></div>
    <div className="card p-5"><p className="eyebrow">Profit waterfall</p><div className="mt-3"><Waterfall label="Gross seller revenue" value={t.grossRevenue} positive/><Waterfall label="Etsy base fees" value={t.etsyBaseFees}/><Waterfall label="Seller-fee VAT" value={t.etsyFeeVatUsd}/><Waterfall label="International shipping" value={t.internationalShippingUsd}/><Waterfall label="Customs & tariffs" value={t.customsAndTariffUsd}/><Waterfall label="Product + labor" value={t.directProductCostUsd}/><Waterfall label="Business overhead" value={t.allocatedBusinessOverheadUsd}/></div></div>
    <details className="card group"><summary className="flex cursor-pointer list-none items-center justify-between p-5"><div><p className="font-semibold">Calculation inspector</p><p className="mt-1 text-xs text-stone-400">{result.lines.length} auditable lines</p></div><ChevronDown className="transition group-open:rotate-180" size={17}/></summary><div className="max-h-[420px] overflow-auto border-t px-5 pb-3">{result.lines.map((line, i) => <div key={`${line.name}-${i}`} className="border-b py-3 last:border-0"><div className="flex justify-between gap-3 text-sm"><span>{line.name}</span><strong>{line.nativeCurrency === "USD" ? "$" : "₺"}{new Decimal(line.nativeAmount).toFixed(2)}</strong></div><p className="mt-1 text-[11px] leading-4 text-stone-400">{line.formula}{line.base ? ` · Base ${line.base}` : ""}{line.rate ? ` · Rate ${line.rate}%` : ""} · @ {result.assumptions[0].replace("USD/TRY snapshot: ", "")}</p></div>)}</div></details>
    <div className="rounded-xl border border-sky-200 bg-sky-50 p-4"><p className="text-xs font-semibold text-sky-900">Assumptions used</p><ul className="mt-2 space-y-1 text-xs leading-5 text-sky-800/80">{result.assumptions.map((a) => <li key={a}>• {a}</li>)}</ul></div>
  </aside>;
}
function ResultStat({ label, value }: { label: string; value: string }) { return <div className="bg-[#18342e] p-4"><p className="text-[10px] text-white/45">{label}</p><p className="mt-1 text-sm font-semibold">{value}</p></div>; }
function Waterfall({ label, value, positive }: { label: string; value: Decimal; positive?: boolean }) { return <div className="flex items-center border-b py-2.5 text-sm last:border-0"><span className={`mr-2 h-1.5 w-1.5 rounded-full ${positive ? "bg-jade" : "bg-coral"}`}/><span className="flex-1 text-stone-600">{label}</span><span className="font-medium">{positive ? "" : "−"}${value.toFixed(2)}</span></div>; }

function ReverseView({ input, targetProfit, targetMargin, setTargetProfit, setTargetMargin, reverseProfit, reverseMargin }: { input: CalculatorInput; targetProfit: string; targetMargin: string; setTargetProfit: (v:string)=>void; setTargetMargin:(v:string)=>void; reverseProfit: Decimal; reverseMargin: Decimal }) {
  const psychological = (v: Decimal) => v.ceil().minus("0.01");
  const scenarios = [["No Offsite Ads", false, "0"], ["Offsite Ads · 15%", true, "15"], ["Offsite Ads · 12%", true, "12"]] as const;
  return <div className="grid gap-5 xl:grid-cols-[.7fr_1.3fr]"><div className="card p-6"><p className="eyebrow">Your target</p><h2 className="mt-1 text-xl font-semibold">Solve backwards</h2><div className="mt-6 space-y-5"><NumberField label="Desired profit after reserves" value={targetProfit} suffix="USD" onChange={setTargetProfit}/><NumberField label="Desired after-reserve margin" value={targetMargin} suffix="%" onChange={setTargetMargin}/></div><p className="mt-6 text-xs leading-5 text-stone-500">Binary search range $0.01–$10,000 · $0.01 tolerance · up to 200 iterations.</p></div><div className="space-y-5"><div className="grid gap-4 sm:grid-cols-2"><PriceCard title="Target profit price" exact={reverseProfit} rounded={psychological(reverseProfit)}/><PriceCard title="Target margin price" exact={reverseMargin} rounded={psychological(reverseMargin)}/></div><div className="card overflow-hidden"><div className="border-b p-5"><p className="eyebrow">Recommended-price scenarios</p><h3 className="mt-1 font-semibold">Offsite Ads impact</h3></div>{scenarios.map(([label, on, rate]) => { const price = solvePrice({ ...input, offsiteAdAttributed: on, offsiteAdsRate: rate }, { kind: "profitUsd", value: targetProfit || 0 }); return <div key={label} className="flex items-center justify-between border-b px-5 py-4 last:border-0"><div><p className="text-sm font-medium">{label}</p><p className="mt-1 text-xs text-stone-400">Exact {formatMoney(price, "USD")}</p></div><strong className="text-lg">{formatMoney(psychological(price), "USD")}</strong></div>; })}</div></div></div>;
}
function PriceCard({ title, exact, rounded }: { title: string; exact: Decimal; rounded: Decimal }) { return <div className="card p-5"><p className="text-xs text-stone-500">{title}</p><p className="mt-2 text-3xl font-semibold">{formatMoney(exact, "USD")}</p><div className="mt-4 flex items-center justify-between rounded-xl bg-cream p-3 text-sm"><span>Psychological</span><strong>{formatMoney(rounded, "USD")}</strong></div></div>; }

function CompanyView({ input }: { input: CalculatorInput }) {
  const profiles = [
    { name: "Individual", subtitle: "No VAT ID · Etsy VAT on", vat: true, overhead: "0", status: "INDIVIDUAL_UNREGISTERED" as const },
    { name: "Sole proprietorship", subtitle: "VAT ID submitted · overhead", vat: false, overhead: "8000", status: "SOLE_PROPRIETORSHIP" as const },
    { name: "Registered · VAT ID pending", subtitle: "Etsy VAT may continue", vat: true, overhead: "8000", status: "SOLE_PROPRIETORSHIP" as const },
  ];
  return <div><div className="mb-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><AlertTriangle className="mr-2 inline" size={16}/> Local VAT, reverse-charge, income-tax, invoicing, or accounting obligations may still apply. Enter accountant-confirmed amounts separately.</div><div className="grid gap-5 lg:grid-cols-3">{profiles.map((profile) => { const calc = calculate({ ...input, businessStatus: profile.status, vatTreatment: profile.vat ? "CHARGED_BY_ETSY" : "NOT_CHARGED_BY_ETSY", monthlyOverheadTry: profile.overhead }); return <div key={profile.name} className="card overflow-hidden"><div className="border-b p-5"><span className={`pill ${profile.vat ? "border-amber-200 bg-amber-50 text-amber-700" : "border-emerald-200 bg-emerald-50 text-emerald-700"}`}>{profile.vat ? "Etsy fee VAT on" : "Etsy fee VAT off"}</span><h3 className="mt-4 text-lg font-semibold">{profile.name}</h3><p className="mt-1 text-xs text-stone-400">{profile.subtitle}</p></div><div className="space-y-3 p-5"><Compare label="Seller-fee VAT" value={formatMoney(calc.totals.etsyFeeVatUsd, "USD")}/><Compare label="Overhead allocation" value={formatMoney(calc.totals.allocatedBusinessOverheadUsd, "USD")}/><Compare label="Contribution profit" value={formatMoney(calc.totals.contributionProfit, "USD")}/><Compare label="Operating profit" value={formatMoney(calc.totals.operatingProfit, "USD")}/><div className="mt-3 rounded-xl bg-[#18342e] p-4 text-white"><p className="text-[10px] text-white/50">Estimated profit after reserves</p><p className="mt-1 text-2xl font-semibold">{formatMoney(calc.totals.estimatedAfterReserveProfit, "USD")}</p></div></div></div>; })}</div><p className="mt-5 text-xs text-stone-500">This comparison does not determine which legal status is best. Monthly costs and tax treatment must be confirmed with a qualified accountant.</p></div>;
}
function Compare({ label, value }: { label: string; value: string }) { return <div className="flex justify-between border-b pb-3 text-sm"><span className="text-stone-500">{label}</span><strong>{value}</strong></div>; }
