import Link from "next/link";
import { ArrowUpRight, BadgeCheck, Clock3, Download, Plus, TriangleAlert } from "lucide-react";

export type Row = { primary: string; secondary: string; badge: string; values: string[] };
export function SectionPage({ eyebrow, title, description, action, columns, rows, stats, warning, children }: { eyebrow: string; title: string; description: string; action: string; columns: string[]; rows: Row[]; stats: { label: string; value: string; note: string }[]; warning?: string; children?: React.ReactNode }) {
  return <div className="mx-auto max-w-[1440px] space-y-6"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">{eyebrow}</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.035em]">{title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-stone-500">{description}</p></div><button className="inline-flex items-center justify-center gap-2 rounded-xl bg-jade px-4 py-2.5 text-sm font-medium text-white"><Plus size={16}/>{action}</button></header>
    {warning && <div className="flex gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><TriangleAlert className="shrink-0" size={18}/><span>{warning}</span></div>}
    <section className="grid gap-3 sm:grid-cols-3">{stats.map((stat) => <div key={stat.label} className="card p-5"><p className="text-xs text-stone-500">{stat.label}</p><p className="mt-2 text-2xl font-semibold tracking-tight">{stat.value}</p><p className="mt-1 text-xs text-stone-400">{stat.note}</p></div>)}</section>
    {children}
    <section className="card overflow-hidden"><div className="flex items-center justify-between border-b p-5"><div><p className="eyebrow">Local records</p><h2 className="mt-1 font-semibold">Saved & versioned</h2></div><button className="inline-flex items-center gap-2 text-xs font-medium text-jade"><Download size={14}/> CSV export</button></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-stone-50 text-[10px] uppercase tracking-[.12em] text-stone-400"><tr><th className="px-5 py-3 font-medium">Record</th>{columns.map((c) => <th className="px-4 py-3 font-medium" key={c}>{c}</th>)}<th className="px-5 py-3"></th></tr></thead><tbody>{rows.map((row) => <tr key={row.primary} className="border-t first:border-t-0 hover:bg-stone-50/50"><td className="px-5 py-4"><p className="font-medium">{row.primary}</p><p className="mt-1 text-xs text-stone-400">{row.secondary}</p></td>{row.values.map((v, i) => <td key={i} className="px-4 py-4 text-stone-600">{i === 0 ? <span className="pill border-stone-200 bg-stone-50"><BadgeCheck size={12}/>{v}</span> : v}</td>)}<td className="px-5 py-4 text-right"><button aria-label={`Open ${row.primary}`}><ArrowUpRight size={16} className="text-stone-400"/></button></td></tr>)}</tbody></table></div>{rows.length === 0 && <div className="p-10 text-center text-sm text-stone-400">No records yet.</div>}</section>
    <div className="flex items-center gap-2 text-xs text-stone-400"><Clock3 size={13}/> Effective dates and immutable snapshots preserve historical calculations.</div>
  </div>;
}

export function InfoGrid({ items }: { items: { title: string; body: string; href?: string }[] }) { return <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map((item) => <div className="card p-5" key={item.title}><h3 className="font-semibold">{item.title}</h3><p className="mt-2 text-sm leading-6 text-stone-500">{item.body}</p>{item.href && <Link href={item.href} className="mt-4 inline-flex items-center gap-1 text-xs font-medium text-jade">Open workspace <ArrowUpRight size={13}/></Link>}</div>)}</div>; }
