ALTER TABLE "ProductCostVersion"
  ADD COLUMN "economicHourlyRateTry" DECIMAL(65,30);

ALTER TABLE "BusinessPersonRole"
  ADD COLUMN "economicHourlyRateTry" DECIMAL(65,30);

ALTER TABLE "CostAssumptionProfile"
  ADD COLUMN "globalEconomicHourlyRateTry" DECIMAL(65,30),
  ADD COLUMN "minimumCashProfitUsd" DECIMAL(65,30) NOT NULL DEFAULT 15,
  ADD COLUMN "minimumEconomicProfitUsd" DECIMAL(65,30) NOT NULL DEFAULT 15,
  ADD COLUMN "minimumCashMarginPercent" DECIMAL(65,30) NOT NULL DEFAULT 10,
  ADD COLUMN "minimumEconomicMarginPercent" DECIMAL(65,30) NOT NULL DEFAULT 10,
  ADD COLUMN "minimumCashProfitPerHourUsd" DECIMAL(65,30) NOT NULL DEFAULT 10,
  ADD COLUMN "minimumEconomicProfitPerHourUsd" DECIMAL(65,30) NOT NULL DEFAULT 10,
  ADD COLUMN "gradeAProfitUsd" DECIMAL(65,30) NOT NULL DEFAULT 50,
  ADD COLUMN "gradeAMarginPercent" DECIMAL(65,30) NOT NULL DEFAULT 25,
  ADD COLUMN "gradeBProfitUsd" DECIMAL(65,30) NOT NULL DEFAULT 30,
  ADD COLUMN "gradeBMarginPercent" DECIMAL(65,30) NOT NULL DEFAULT 15,
  ADD COLUMN "gradeCProfitUsd" DECIMAL(65,30) NOT NULL DEFAULT 20,
  ADD COLUMN "gradeCMarginPercent" DECIMAL(65,30) NOT NULL DEFAULT 10,
  ADD COLUMN "criticalMarginPercent" DECIMAL(65,30) NOT NULL DEFAULT 5,
  ADD COLUMN "lowProfitUsd" DECIMAL(65,30) NOT NULL DEFAULT 15,
  ADD COLUMN "shippingHeavyPercent" DECIMAL(65,30) NOT NULL DEFAULT 25,
  ADD COLUMN "overheadHeavyPercent" DECIMAL(65,30) NOT NULL DEFAULT 20;
