import Link from "next/link";
import { restartOnboardingAction } from "./actions";
import { saveExchangeRateAction, saveReportingCurrencyAction, saveWorkspaceShippingAction } from "../profitability-actions";
import { requireWorkspaceContext } from "@/lib/server/auth/workspace-context";
import { loadProfitability } from "@/lib/server/services/profitability-service";

export default async function SaasSettingsPage(){const view=await loadProfitability(await requireWorkspaceContext());const destination=view.destination;const shipping=view.shippingDefaults.find((row)=>row.destinationCountry===destination);const reporting=view.businessProfile?.reportingCurrency??view.costDefault?.reportingCurrency??"USD";const now=new Date().toISOString();return <div className="mx-auto max-w-5xl space-y-6"><header><p className="eyebrow">Workspace settings</p><h1 className="mt-2 text-3xl font-semibold">Kârlılık ayarları</h1><p className="mt-2 text-sm text-stone-600">Yeni değerler sürümlenir. Eski hesaplama snapshot’ları güncel kur veya kargo ayarlarıyla değiştirilmez.</p></header><div className="grid gap-4 lg:grid-cols-2">
  <section className="card p-5"><h2 className="font-semibold">Kargo ve hedef marj · {destination}</h2><form action={saveWorkspaceShippingAction} className="mt-4 grid gap-3 sm:grid-cols-2"><Field name="destinationCountry" label="Hedef ülke" value={destination}/><Field name="shippingCost" label="Ortalama kargo (bilinmiyorsa boş)" value={shipping?.shippingCost?.toString()??view.costDefault?.defaultShippingCost?.toString()} required={false}/><Field name="shippingCurrency" label="Kargo para birimi" value={shipping?.shippingCurrency??view.costDefault?.defaultShippingCurrency??view.costDefault?.costCurrency??"TRY"}/><label className="text-sm">Gümrük sorumluluğu<select name="customsResponsibility" defaultValue={shipping?.customsResponsibility??view.costDefault?.customsResponsibility??"UNKNOWN"} className="mt-1 w-full rounded-lg border px-3 py-2"><option>UNKNOWN</option><option>SELLER</option><option>BUYER</option></select></label><Field name="sellerPaidCustomsCost" label="Satıcı gümrük maliyeti" value={shipping?.sellerPaidCustomsCost?.toString()} required={false}/><Field name="customsCurrency" label="Gümrük para birimi" value={shipping?.customsCurrency??view.costDefault?.marketplaceCurrency??"USD"} required={false}/><Field name="targetMarginPercent" label="Hedef nakit marjı %" value={shipping?.targetMarginPercent.toString()??"20"}/><button className="rounded-xl border bg-white px-4 py-2.5 text-sm font-medium sm:col-span-2">Yeni ayar sürümü oluştur</button></form></section>
  <section className="card p-5"><h2 className="font-semibold">Manuel kur snapshot’ı</h2><p className="mt-2 text-xs text-stone-500">Yalnız bildiğiniz gözlem değerini girin. Sistem kur uydurmaz veya geçmişi yeniden yazmaz.</p><form action={saveExchangeRateAction} className="mt-4 grid gap-3 sm:grid-cols-2"><Field name="baseCurrency" label="Baz para" value={view.costDefault?.marketplaceCurrency??"USD"}/><Field name="quoteCurrency" label="Karşıt para" value={view.costDefault?.costCurrency??"TRY"}/><Field name="rate" label="Kur"/><input type="hidden" name="capturedAt" value={now}/><button className="rounded-xl border bg-white px-4 py-2.5 text-sm font-medium sm:col-span-2">Kur snapshot’ı kaydet</button></form><div className="mt-4 border-t pt-4"><form action={saveReportingCurrencyAction} className="flex items-end gap-3"><Field name="reportingCurrency" label="Raporlama para birimi" value={reporting}/><button className="rounded-xl border bg-white px-4 py-2.5 text-sm font-medium">Sürümle</button></form></div></section>
  <section className="card p-5"><h2 className="font-semibold">Başlangıç ayarları</h2><p className="mt-2 text-sm text-stone-600">Onboarding’i yeniden açmak ürünleri, maliyet sürümlerini veya Etsy verilerini silmez.</p><form action={restartOnboardingAction}><button className="mt-4 rounded-xl border bg-white px-4 py-2.5 text-sm font-medium">Başlangıç ayarlarını düzenle</button></form></section><section className="card p-5"><h2 className="font-semibold">Etsy</h2><Link className="mt-3 inline-flex text-sm underline" href="/app/settings/etsy">Bağlantı ve senkronizasyon ayarları</Link></section>
  </div></div>}
function Field({name,label,value,required=true}:{name:string;label:string;value?:string;required?:boolean}){return <label className="min-w-0 text-sm">{label}<input name={name} required={required} defaultValue={value??""} className="mt-1 w-full rounded-lg border px-3 py-2"/></label>}
