import Link from "next/link";
import { requireWorkspaceContext } from "@/lib/server/auth/workspace-context";
import { loadProfitability } from "@/lib/server/services/profitability-service";

export default async function SaasProductsPage({ searchParams }: { searchParams: Promise<{ status?: string }> }) {
  const view = await loadProfitability(await requireWorkspaceContext());
  const { status } = await searchParams;
  const shown = status === "needs-attention" ? view.products.filter((row) => row.calculation.result === null) : view.products;
  return <div className="mx-auto max-w-6xl space-y-6"><header><p className="eyebrow">Products</p><h1 className="mt-2 text-3xl font-semibold">Ürün kârlılığı</h1><p className="mt-2 text-sm text-stone-600">Her ürün kendi fiyatı ve maliyetleriyle hesaplanır; eksik kayıtlar toplamdan çıkarılır.</p></header><div className="flex gap-2 text-sm"><Link className="rounded-lg border bg-white px-3 py-2" href="/app/products">Tümü</Link><Link className="rounded-lg border bg-white px-3 py-2" href="/app/products?status=needs-attention">Eksik bilgili</Link></div><div className="overflow-hidden rounded-2xl border border-stone-200 bg-white"><div className="hidden grid-cols-[minmax(0,2fr)_1fr_1fr_1fr_120px] gap-4 border-b bg-stone-50 px-4 py-3 text-xs font-medium text-stone-500 md:grid"><span>Ürün / ilan</span><span>Nakit kâr</span><span>Ekonomik kâr</span><span>Marj / not</span><span>Durum</span></div>{shown.map(({product,calculation}) => { const listing=product.etsyListingLinks[0]?.listing; const result=calculation.result; return <Link href={`/app/products/${product.id}`} className="grid gap-2 border-b px-4 py-4 last:border-0 md:grid-cols-[minmax(0,2fr)_1fr_1fr_1fr_120px] md:items-center md:gap-4" key={product.id}><div className="min-w-0"><h2 className="truncate font-medium">{product.title}</h2><p className="mt-1 text-xs text-stone-500">{listing ? `${listing.priceAmount.toString()} ${listing.priceCurrency} · ${listing.state}` : "İlan bağlantısı eksik"}</p></div><Value value={result?.finalCashProfit.toDecimalPlaces(2).toString()} currency={result?.reportingCurrency}/><Value value={result?.economicProfit?.toDecimalPlaces(2).toString()} currency={result?.reportingCurrency}/><span className="text-sm">{result?.cashMarginPercent ? `%${result.cashMarginPercent.toDecimalPlaces(1).toString()} · ${result.finalCashProfit.lt(0)?"D":result.cashMarginPercent.gte(25)?"A":result.cashMarginPercent.gte(15)?"B":"C"}` : "—"}</span><span className={`pill w-fit ${result?"border-emerald-200 bg-emerald-50 text-emerald-800":"border-amber-200 bg-amber-50 text-amber-800"}`}>{calculation.status}</span></Link>; })}</div></div>;
}
function Value({value,currency}:{value?:string|null;currency?:string}) { return <span className="text-sm font-medium">{value == null ? "—" : `${value} ${currency}`}</span>; }
